version: '3.8'

services:
  optica:
    container_name: optica
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/optics
    ports:
      - "8888:8888"
    command: ["jupyter", "lab", "--ip='*'", "--port=8888", "--no-browser", "--allow-root"]

